FROM node:16-alpine

# Build time args to be passed as env variables
# ARG MONGO_URI
# ARG ISSUER_BASE_URL
# ARG OAUTH_CLIENT_ID
# ARG OAUTH_REDIRECT_URI
# ARG OAUTH_CLIENT_SECRET
# ARG UNSPLASH_API_KEY
# ARG JWT_SECRET
# ARG CLOUDINARY_URL
# ARG CLOUDINARY_ASSET_URL

# With default values
ENV ALLOWED_URLS=https://thullo.fredkiss.dev
ENV PORT=80

WORKDIR /webapp

RUN apk add --update curl && rm -rf /var/cache/apk/*
RUN curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@6

COPY ./package.json ./
COPY ./pnpm-lock.yaml ./
COPY ./packages/domain/package.json ./packages/domain/package.json
COPY ./packages/adapters/package.json ./packages/adapters/package.json
COPY ./packages/express/package.json ./packages/express/package.json

RUN FORCE_COLOR=true pnpm install --shamefully-hoist --frozen-lockfile

ENV NODE_ENV=production

COPY ./packages/domain/dist ./packages/domain/dist
COPY ./packages/adapters/dist ./packages/adapters/dist
COPY ./packages/express/dist ./packages/express/dist


CMD [ "pnpm", "run", "start", "--prefix", "packages/express" ]