FROM node:20-alpine

# Build time args to be passed as env variables
# ARG MONGO_URI
# ARG ISSUER_BASE_URL
# ARG OAUTH_CLIENT_ID
# ARG OAUTH_REDIRECT_URI
# ARG OAUTH_CLIENT_SECRET
# ARG UNSPLASH_API_KEY
# ARG JWT_SECRET
# ARG CLOUDINARY_URL
# ARG CLOUDINARY_ASSET_URL
ARG TURBO_TEAM
ENV TURBO_TEAM=$TURBO_TEAM

ARG TURBO_TOKEN
ENV TURBO_TOKEN=$TURBO_TOKEN

ENV ALLOWED_URLS=https://thullo.fredkiss.dev
ENV PORT=80

WORKDIR /webapp

RUN apk add --update curl && rm -rf /var/cache/apk/*
RUN npm install --global pnpm@8.15.9

COPY turbo.json ./
COPY .turbo/config.json ./.turbo/

COPY ./* ./
COPY ./packages/ ./packages/
COPY ./apps/ ./apps/

RUN pnpm install --frozen-lockfile

RUN FORCE_COLOR=true TURBO_API="https://thullo-turbo-remote-cache-docker.fkiss.me" TURBO_TOKEN=$TURBO_TOKEN TURBO_TEAM="fredkiss3" pnpm turbo build --filter @thullo/api

ENV NODE_ENV=production

CMD [ "pnpm", "run", "start", "--prefix", "packages/express" ]