import { Helmet } from 'react-helmet';

export interface SeoProps {
    title?: string;
}

export function Seo({ title }: SeoProps) {
    return (
        <Helmet>
            <title>{`${title ?? 'A Full Stack Trello Clone'} - Thullo`}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Helmet>
    );
}
