import { Helmet } from 'react-helmet';

export interface SeoProps {
    title?: string;
}

export function Seo({ title }: SeoProps) {
    return (
        <Helmet>
            <title>{`${title ?? 'A Full Stack Trello Clone'} - Thullo`}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <script
                async
                defer
                data-website-id="b609746d-2ca7-4be3-be87-cb1555ed2205"
                src="https://monitor.fredkiss.dev/umami.js"
            />
        </Helmet>
    );
}
