import Head from "next/head";

export interface SeoProps {
  title?: string;
}

export const Seo: React.FC<SeoProps> = ({ title }) => {
  return (
    <Head>
      <title>{`${title ?? 'A Full Stack Trello Clone'} - Thullo`}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};
