# This is a basic workflow to help you get started with Actions

name: CI/CD For the Frontend

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths:
      - "packages/front/**"
      - .github/workflows/front.yml
    branches:
      - develop

  # Allows you to run this workflow manually from the Actions tab+1
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   environment: dev

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Setup pnpm
  #       uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
  #       with:
  #         version: 6.22.2

  #     - name: Setup Node version
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: 16.x
  #         cache: "pnpm"

  #     - name: Install dependencies
  #       run: FORCE_COLOR=true pnpm i --prefix packages/front

  #     - name: Test the frontend
  #       run: FORCE_COLOR=true pnpm run test --prefix packages/front

  deploy:
    # needs: test
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: dev

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 6.22.2

      - name: Setup Node version
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "pnpm"

      - name: Install dependencies
        run: FORCE_COLOR=true pnpm i --prefix packages/front

      - name: Publish the frontend
        run: FORCE_COLOR=true pnpm run deploy --prefix packages/front
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          VITE_API_URL: ${{ secrets.API_URL }}
